server:
  port: 28019
dubbo:
  application:
    name: dubbo-integration-controller
  registry:
    # 模拟存量dubbo应用注册到zookeeper的情况，新开发的应用建议配置为 sc://127.0.0.1:30100
    address: zookeeper://127.0.0.1:2181
    protocol: zookeeper
    # dubbo3.x注册类型支持interface/instance/all,默认为all
    register-mode: ${DUBBO_REGISTRY_MODE:all}

spring:
  application:
    name: dubbo-integration-controller

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

management:
  endpoint:
    health:
      probes:
        enabled: true