name: "Common operations"
description: "do something common for all test"
runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ env.javaVersion }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.javaVersion }}
        distribution: 'adopt'
        cache: maven
    - name: download middlewares
      uses: actions/cache@v3
      with:
        path: |
          apache-zookeeper-*/
          Local-CSE-2.1.3-linux-amd64.zip
        key: ${{ runner.os }}-middlewares-${{ github.run_id }}
    - name: download agent
      uses: actions/cache@v3
      with:
        path: sermant-agent-*/
        key: ${{ runner.os }}-agent-${{ github.run_id }}
    - name: start zookeeper
      shell: bash
      run: bash apache-zookeeper-3.6.3-bin/bin/zkServer.sh start apache-zookeeper-3.6.3-bin/conf/zoo_sample.cfg
    - name: start cse
      shell: bash
      run: |
        export ROOT_PATH=$(pwd)
        bash ./sermant-integration-tests/scripts/startCse.sh
    - name: cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: plugin change check
      uses: ./.github/actions/common/plugin-change-check
    - name: adaptation for dubbo 2.5.0 - 2.5.6
      shell: bash
      if: matrix.dubbo-version == '2-5' && matrix.dubbo-versions < 7
      run: |
        sed -i '/dubbo:parameter/d' sermant-integration-tests/dubbo-test/dubbo-2-6-integration-consumer/src/main/resources/dubbo/dubbo.xml
        sed -i '/\/dubbo:application/d' sermant-integration-tests/dubbo-test/dubbo-2-6-integration-consumer/src/main/resources/dubbo/dubbo.xml
        sed -i 's/<dubbo:application name="dubbo-integration-consumer">/<dubbo:application name="dubbo-integration-consumer"\/>/' sermant-integration-tests/dubbo-test/dubbo-2-6-integration-consumer/src/main/resources/dubbo/dubbo.xml
        sed -i '/dubbo:parameter/d' sermant-integration-tests/dubbo-test/dubbo-2-6-integration-controller/src/main/resources/dubbo/consumer.xml
        sed -i '/\/dubbo:application/d' sermant-integration-tests/dubbo-test/dubbo-2-6-integration-controller/src/main/resources/dubbo/consumer.xml
        sed -i 's/<dubbo:application name="dubbo-integration-controller">/<dubbo:application name="dubbo-integration-controller"\/>/' sermant-integration-tests/dubbo-test/dubbo-2-6-integration-controller/src/main/resources/dubbo/consumer.xml
        sed -i '/dubbo:parameter/d' sermant-integration-tests/dubbo-test/dubbo-2-6-integration-provider/src/main/resources/dubbo/provider.xml
        sed -i '/\/dubbo:application/d' sermant-integration-tests/dubbo-test/dubbo-2-6-integration-provider/src/main/resources/dubbo/provider.xml
        sed -i 's/<dubbo:application name="dubbo-integration-provider">/<dubbo:application name="dubbo-integration-provider"\/>/' sermant-integration-tests/dubbo-test/dubbo-2-6-integration-provider/src/main/resources/dubbo/provider.xml
    - name: configuration for 2.5.x - 2.6.x
      if: matrix.dubbo-version == '2-5' || matrix.dubbo-version == '2-6'
      shell: bash
      run: echo "projectPath=2-6" >> $GITHUB_ENV
    - name: configuration for 2.7.x
      if: matrix.dubbo-version == '2-7' || matrix.dubbo-version == '3-0' || matrix.dubbo-version == '3-1' || matrix.dubbo-version == '3-2'
      shell: bash
      run: echo "projectPath=2-7" >> $GITHUB_ENV